# Generated by Django 4.2.9 on 2026-02-21 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la machine')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence')),
                ('localisation', models.CharField(max_length=200, verbose_name='Localisation / Zone')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
                ('date_installation', models.DateField(blank=True, null=True, verbose_name="Date d'installation")),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre du ticket')),
                ('description', models.TextField(verbose_name='Description de la panne')),
                ('type_panne', models.CharField(choices=[('mecanique', '⚙️ Mécanique'), ('electrique', '⚡ Électrique'), ('electronique', '💻 Électronique'), ('pneumatique', '💨 Pneumatique'), ('hydraulique', '💧 Hydraulique'), ('logiciel', '🖥️ Logiciel'), ('autre', '🔧 Autre')], max_length=20, verbose_name='Type de panne')),
                ('priorite', models.CharField(choices=[('critique', '🔴 Critique'), ('haute', '🟠 Haute'), ('moyenne', '🟡 Moyenne'), ('basse', '🟢 Basse')], default='moyenne', max_length=10, verbose_name='Priorité')),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('en_attente', 'En attente pièces'), ('resolu', 'Résolu'), ('ferme', 'Fermé')], default='ouvert', max_length=15, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('date_resolution', models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution')),
                ('solution', models.TextField(blank=True, verbose_name='Solution appliquée')),
                ('pieces_remplacees', models.TextField(blank=True, verbose_name='Pièces remplacées')),
                ('temps_intervention', models.PositiveIntegerField(blank=True, null=True, verbose_name="Temps d'intervention (minutes)")),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assignes', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.machine', verbose_name='Machine')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='tickets.ticket')),
            ],
            options={
                'ordering': ['date_creation'],
            },
        ),
    ]
