# Generated by Django 6.0.3 on 2026-04-13 12:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('allowed_types', models.CharField(blank=True, help_text='Clés de `type_panne` séparées par des virgules', max_length=300)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la machine')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence')),
                ('localisation', models.CharField(max_length=200, verbose_name='Localisation / Zone')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
                ('date_installation', models.DateField(blank=True, null=True, verbose_name="Date d'installation")),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.department', verbose_name='Département associé')),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='OperatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('operateur', 'Opérateur'), ('superviseur', 'Superviseur')], default='operateur', max_length=20)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.department')),
                ('machines', models.ManyToManyField(blank=True, to='tickets.machine', verbose_name="Machines de l'opérateur")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operatorprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil opérateur',
                'verbose_name_plural': 'Profils opérateurs',
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.operatorprofile', verbose_name='Opérateur assigné'),
        ),
        migrations.CreateModel(
            name='TicketSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Sans titre', max_length=200, verbose_name='Titre du ticket')),
                ('categorie', models.CharField(choices=[('industrielle', 'Industrielle'), ('informatique', 'Informatique')], default='industrielle', max_length=30, verbose_name='Catégorie')),
                ('type_panne', models.CharField(default='Non renseigné', max_length=100, verbose_name='Type de panne')),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('moyenne', 'Moyenne'), ('haute', 'Haute')], default='moyenne', max_length=10, verbose_name='Priorité')),
                ('numero_ticket', models.CharField(max_length=50, unique=True, verbose_name='N° de ticket')),
                ('service_support', models.CharField(max_length=200, verbose_name='Service support')),
                ('demandeur', models.CharField(max_length=200, verbose_name='Nom du demandeur')),
                ('code_machine', models.CharField(max_length=100, verbose_name='Code machine')),
                ('date_ticket', models.DateField(verbose_name='Date du ticket')),
                ('heure_ticket', models.TimeField(verbose_name='Heure du ticket')),
                ('delai_souhaite', models.DateField(blank=True, null=True, verbose_name='Délai souhaité')),
                ('type_support', models.BooleanField(default=False, verbose_name='Curative (décocher) / Préventive (cocher)')),
                ('description_probleme', models.TextField(verbose_name='Description du problème')),
                ('nature_probleme', models.CharField(choices=[('mecanique', 'Mécanique'), ('electrique', 'Électrique'), ('hydraulique', 'Hydraulique'), ('pneumatique', 'Pneumatique'), ('informatique', 'Informatique'), ('autre', 'Autre')], max_length=20, verbose_name='Nature du problème')),
                ('visa_demandeur', models.CharField(blank=True, max_length=200, verbose_name='Visa du demandeur')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.machine', verbose_name='Machine concernée')),
            ],
            options={
                'verbose_name': 'Ticket de support',
                'verbose_name_plural': 'Tickets de support',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='InterventionTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_technicien', models.CharField(choices=[('interne', 'Interne'), ('externe', 'Externe')], max_length=10, verbose_name='Type de technicien')),
                ('nom_technicien', models.CharField(blank=True, max_length=200, verbose_name='Nom du technicien maintenance')),
                ('nom_prestataire', models.CharField(blank=True, max_length=200, verbose_name='Nom du prestataire')),
                ('nom_accompagnant', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'accompagnant")),
                ('date_prise_en_compte', models.DateField(default=django.utils.timezone.now, verbose_name='Date de prise en compte')),
                ('heure_prise_en_compte', models.TimeField(default=django.utils.timezone.now, verbose_name='Heure de prise en compte')),
                ('description_intervention', models.TextField(verbose_name="Description détaillée de l'intervention")),
                ('date_fin_intervention', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('heure_fin_intervention', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('visa_technicien', models.CharField(blank=True, max_length=200, verbose_name='Visa du technicien')),
                ('approbation_fin', models.CharField(blank=True, max_length=200, verbose_name='Nom du demandeur approuvant la fin')),
                ('visa_approbation', models.CharField(blank=True, max_length=200, verbose_name="Visa de l'approbateur")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('numero_ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.ticketsupport', verbose_name='N° de ticket')),
            ],
            options={
                'verbose_name': 'Intervention technique',
                'verbose_name_plural': 'Interventions techniques',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='TicketSupportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='tickets/files/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='tickets.ticketsupport')),
            ],
        ),
    ]
