# Generated by Django 4.2.9 on 2026-02-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='categorie_ticket',
            field=models.CharField(choices=[('industrielle', '🏭 Panne industrielle'), ('bureautique', '🖥️ Panne bureautique')], default='industrielle', max_length=15, verbose_name='Catégorie de ticket'),
        ),
    ]
