# Generated by Django 4.2.30 on 2026-04-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('operateur', 'Opérateur'), ('superviseur', 'Superviseur')], default='operateur', max_length=20),
        ),
    ]
