# Generated by Django 4.2.9 on 2026-02-23 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_categorie_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.machine', verbose_name='Machine'),
        ),
    ]
