# Generated by Django 4.2.30 on 2026-04-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', help_text='Nom du profil SMTP', max_length=100, unique=True)),
                ('host', models.CharField(help_text='Adresse du serveur SMTP', max_length=255)),
                ('port', models.PositiveIntegerField(default=587, help_text='Port SMTP')),
                ('username', models.CharField(help_text="Nom d'utilisateur SMTP", max_length=255)),
                ('password', models.CharField(help_text='Mot de passe SMTP', max_length=255)),
                ('use_tls', models.BooleanField(default=True, help_text='Utiliser TLS')),
                ('use_ssl', models.BooleanField(default=False, help_text='Utiliser SSL')),
                ('from_email', models.EmailField(help_text="Adresse email d'expédition", max_length=254)),
                ('active', models.BooleanField(default=True, help_text='Profil SMTP actif')),
            ],
        ),
    ]
