# Generated by Django 4.2.30 on 2026-04-23 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0004_smtpsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('nouveau_ticket', 'Nouveau ticket'), ('ticket_critique', 'Ticket critique'), ('machine_inactive', 'Machine inactive'), ('intervention_terminee', 'Intervention terminée')], default='nouveau_ticket', max_length=30)),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'alerte")),
                ('message', models.TextField(verbose_name="Message de l'alerte")),
                ('lue', models.BooleanField(default=False, verbose_name='Lue')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('destinataire', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tickets.machine')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tickets.ticketsupport')),
            ],
            options={
                'verbose_name': "Notification d'alerte",
                'verbose_name_plural': "Notifications d'alerte",
                'ordering': ['-date_creation'],
            },
        ),
    ]
