# Generated by Django 4.2.30 on 2026-04-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la pièce')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence pièce')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('quantite', models.PositiveIntegerField(default=0, verbose_name='Quantité disponible')),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
                ('machines', models.ManyToManyField(blank=True, related_name='spare_parts', to='tickets.machine', verbose_name='Machines concernées')),
            ],
            options={
                'verbose_name': 'Pièce de rechange',
                'verbose_name_plural': 'Pièces de rechange',
                'ordering': ['nom'],
            },
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
