# Generated by Django 4.2.30 on 2026-04-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_ticket_view',
            field=models.CharField(choices=[('cards', 'Cartes'), ('list', 'Liste'), ('kanban', 'Kanban')], default='cards', max_length=20, verbose_name='Vue par défaut des tickets'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ticket_filters',
            field=models.JSONField(blank=True, default=dict, verbose_name='Filtres des tickets sauvegardés'),
        ),
    ]
