# Generated by Django 4.2.9 on 2026-02-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_map_type_panne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type_panne',
            field=models.CharField(choices=[('informatique', 'Informatique'), ('maintenance', 'Maintenance'), ('engineer', 'Ingénierie')], max_length=20, verbose_name='Type de panne'),
        ),
    ]
