# Generated by Django 4.2.30 on 2026-04-24 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_sparepart_delete_notification'),
        ('tickets', '0007_userprofile_default_ticket_view_and_more'),
    ]

    operations = [
    ]
