# Generated by Django 4.2.9 on 2026-02-25 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_ticket_type_panne'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_demande', models.CharField(max_length=50, unique=True, verbose_name='N° de demande')),
                ('service_demandeur', models.CharField(max_length=200, verbose_name='Service demandeur')),
                ('demandeur', models.CharField(max_length=200, verbose_name='Nom du demandeur')),
                ('code_machine', models.CharField(max_length=100, verbose_name='Code machine')),
                ('date_demande', models.DateField(verbose_name='Date de demande')),
                ('heure_demande', models.TimeField(verbose_name='Heure de demande')),
                ('delai_souhaite', models.DateField(blank=True, null=True, verbose_name='Délai souhaité')),
                ('type_intervention', models.BooleanField(default=False, verbose_name='Curative (décocher) / Préventive (cocher)')),
                ('description_anomalie', models.TextField(verbose_name="Description de l'anomalie")),
                ('nature_anomalie', models.CharField(choices=[('mecanique', 'Mécanique'), ('electrique', 'Électrique'), ('hydraulique', 'Hydraulique'), ('pneumatique', 'Pneumatique'), ('informatique', 'Informatique'), ('autre', 'Autre')], max_length=20, verbose_name="Nature de l'anomalie")),
                ('visa_demandeur', models.CharField(blank=True, max_length=200, verbose_name='Visa du demandeur')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.machine', verbose_name='Machine concernée')),
            ],
            options={
                'verbose_name': "Demande d'intervention",
                'verbose_name_plural': "Demandes d'intervention",
                'ordering': ['-date_creation'],
            },
        ),
    ]
