# Generated by Django 4.2.30 on 2026-04-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_merge_20260424_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_ticket_view',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ticket_filters',
        ),
    ]
