# Generated by Django 4.2.9 on 2026-02-25 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_demandeintervention'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_technicien', models.CharField(choices=[('interne', 'Interne'), ('externe', 'Externe')], max_length=10, verbose_name='Type de technicien')),
                ('nom_technicien', models.CharField(blank=True, max_length=200, verbose_name='Nom du technicien')),
                ('nom_prestataire', models.CharField(blank=True, max_length=200, verbose_name='Nom du prestataire')),
                ('nom_accompagnant', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'accompagnant")),
                ('date_prise_en_compte', models.DateField(verbose_name='Date de prise en compte')),
                ('heure_prise_en_compte', models.TimeField(verbose_name='Heure de prise en compte')),
                ('date_fin_intervention', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('heure_fin_intervention', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('description_intervention', models.TextField(verbose_name="Description de l'intervention")),
                ('visa_technicien', models.CharField(blank=True, max_length=200, verbose_name='Visa du technicien')),
                ('approbation_fin', models.CharField(blank=True, max_length=200, verbose_name='Approbation de fin')),
                ('visa_approbation', models.CharField(blank=True, max_length=200, verbose_name="Visa de l'approbateur")),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('suspendue', 'Suspendue')], default='planifiee', max_length=15, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.demandeintervention', verbose_name='Demande liée')),
            ],
            options={
                'verbose_name': 'Intervention technique',
                'verbose_name_plural': 'Interventions techniques',
                'ordering': ['-date_creation'],
            },
        ),
    ]
