# Generated by Django 4.2.30 on 2026-04-24 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0009_remove_userprofile_default_ticket_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsupport',
            name='spare_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.sparepart', verbose_name='Pièce détachée réservée'),
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_reservee', models.PositiveIntegerField(default=1, verbose_name='Quantité réservée')),
                ('date_reservation', models.DateTimeField(auto_now_add=True, verbose_name='Date de réservation')),
                ('est_consommee', models.BooleanField(default=False, verbose_name='Consommée')),
                ('date_consommation', models.DateTimeField(blank=True, null=True, verbose_name='Date de consommation')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='tickets.sparepart')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='tickets.ticketsupport')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Réservation de stock',
                'verbose_name_plural': 'Réservations de stock',
                'ordering': ['-date_reservation'],
                'unique_together': {('piece', 'ticket')},
            },
        ),
    ]
