# Generated by Django 4.2.9 on 2026-02-25 09:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_interventiontechnique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interventiontechnique',
            name='demande',
        ),
        migrations.RemoveField(
            model_name='interventiontechnique',
            name='statut',
        ),
        migrations.AddField(
            model_name='interventiontechnique',
            name='numero_demande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.demandeintervention', verbose_name='N° de demande'),
        ),
        migrations.AlterField(
            model_name='interventiontechnique',
            name='approbation_fin',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom du demandeur approuvant la fin'),
        ),
        migrations.AlterField(
            model_name='interventiontechnique',
            name='date_prise_en_compte',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de prise en compte'),
        ),
        migrations.AlterField(
            model_name='interventiontechnique',
            name='description_intervention',
            field=models.TextField(verbose_name="Description détaillée de l'intervention"),
        ),
        migrations.AlterField(
            model_name='interventiontechnique',
            name='heure_prise_en_compte',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Heure de prise en compte'),
        ),
        migrations.AlterField(
            model_name='interventiontechnique',
            name='nom_technicien',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom du technicien maintenance'),
        ),
    ]
