# Generated by Django 4.2.30 on 2026-04-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ticketsupport_spare_part_stockreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='manuel_pdf',
            field=models.FileField(blank=True, null=True, upload_to='machines/manuals/', verbose_name="Manuel d'utilisation (PDF)"),
        ),
        migrations.AddField(
            model_name='machine',
            name='manuel_texte',
            field=models.TextField(blank=True, null=True, verbose_name="Manuel d'utilisation (texte)"),
        ),
    ]
