# Generated by Django 4.2.30 on 2026-05-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsupport',
            name='sla_status',
            field=models.CharField(choices=[('on_time', "🟢 À l'heure"), ('warning', '🟠 Bientôt en retard'), ('overdue', '🔴 En retard')], default='on_time', max_length=10, verbose_name='Statut SLA'),
        ),
    ]
